// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB9XdDjMdVeNfcUCKzPTlgLOcKhpeCKpE',
    appId: '1:901473190754:web:d57db811f62c714706623b',
    messagingSenderId: '901473190754',
    projectId: 'apppppppp-159fd',
    authDomain: 'apppppppp-159fd.firebaseapp.com',
    storageBucket: 'apppppppp-159fd.firebasestorage.app',
    measurementId: 'G-GVVVYFGZBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrmy0iN6Z8GAsm9DidSeN3wH9MZft1y2k',
    appId: '1:901473190754:android:d186646160d4e6f306623b',
    messagingSenderId: '901473190754',
    projectId: 'apppppppp-159fd',
    storageBucket: 'apppppppp-159fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjbdQl_UOQEtX5xINNMro6a_vwnfhBZN0',
    appId: '1:901473190754:ios:449f3a04ab3f5cd706623b',
    messagingSenderId: '901473190754',
    projectId: 'apppppppp-159fd',
    storageBucket: 'apppppppp-159fd.firebasestorage.app',
    iosBundleId: 'com.example.geminiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB9XdDjMdVeNfcUCKzPTlgLOcKhpeCKpE',
    appId: '1:901473190754:web:7a7d1b56e1f055f806623b',
    messagingSenderId: '901473190754',
    projectId: 'apppppppp-159fd',
    authDomain: 'apppppppp-159fd.firebaseapp.com',
    storageBucket: 'apppppppp-159fd.firebasestorage.app',
    measurementId: 'G-KV6NW8T2VK',
  );
}
